---
- name: Install MySQL and Apache
  apt: name={{ item }} state=installed update_cache=yes
  with_items: 
    - apache2
    - mysql-server
  when: limesurvey_with_services

- name: Install dependencies
  apt: name={{ item }} state=installed update_cache=yes
  with_items: limesurvey.deb.dependencies
  notify: reload apache

- name: Download Limesurvey package
  get_url: url={{ limesurvey.url }} dest=/tmp/{{ limesurvey.package }}

- name: Extract Limesurvey package
  unarchive: copy=no src=/tmp/{{ limesurvey.package }} dest={{ limesurvey.web.root }} group=users owner=root creates={{ limesurvey.web.root }}/limesurvey

- name: Fix permissions
  file: path={{ limesurvey.web.root }}/{{ item }} owner={{ limesurvey.web.user }} recurse=yes
  with_items:
    - limesurvey/tmp
    - limesurvey/upload
    - limesurvey/application/config

- name: Create Limesurvey database
  mysql_db: name={{ limesurvey.db.name }} state=present login_host={{ limesurvey.db.host }} login_user={{ limesurvey.db.adminuser }} login_password={{ limesurvey.db.adminpassword }}
  register: limesurvey_db

- name: Transfer SQL file
  template: src=limesurvey.sql.j2 dest=/tmp/limesurvey.sql mode=0600
  when: limesurvey_db|changed

- name: Import empty SQL database
  mysql_db: state=import name={{ limesurvey.db.name }} target=/tmp/limesurvey.sql login_host={{ limesurvey.db.host }} login_user={{ limesurvey.db.adminuser }} login_password={{ limesurvey.db.adminpassword }}
  when: limesurvey_db|changed

- name: Limesurvey database user
  mysql_user: name={{ limesurvey.db.limeuser }} password={{ limesurvey.db.limepassword }} priv={{ limesurvey.db.name }}.*:ALL state=present

- name: Transfer Limesurvey configuration file
  template: src=config.php.j2 dest={{ limesurvey.web.root }}/limesurvey/application/config/config.php owner={{ limesurvey.web.user }} mode=0644